### PR TITLE
Setup CI Test for GitHub

### PR DESCRIPTION
**Pull request by XiaoleiShi-NV**

### CODE REVIEW

**Comment by 4cwfe** [comment]
2414185237
I know everyone is different and i just want to hear your opinions. Is it the act of showing how much you love someone? Is it more of exercise and physical stamina? Is it a way to feelinfo@suodien7raf.mybiz.com pleasure? I imagine it’s different depending on who you sleep with

Personally I don’t think i could have sex with someone i didn’t love, because i view it as a love connection (not judging anyone, you should do whatever you want, as long as it’s consensual) I just want to know how other people view it

**Comment by XiaoleiShi-NV** [comment]
Solve build gossip error by adding `${PROJECT_SOURCE_DIR}/third_party/gossip` to CMakeList.txt
Capture

**Comment by XiaoleiShi-NV** [comment]
@zehuanw This MR is ready to merge, the three tests `Single node tests`, `Multi node tests with NCCL` and `Multi node tests with Gossip` work well.

**Comment by XiaoleiShi-NV** [comment]
Ways for further optimization:
* Support fine-grained control (cancel/restart) to each job: decompose the single `github-ci.yml` file into multiple files, each file is responsible for one job.
* Use artifacts: Coupled with the up-mentioned file-decomposition (https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts)

**Pull request closed without merging**
